import test from 'node:test';import assert from 'node:assert/strict';import {initialState,transition,ACTIONS} from '../skills/woia-scheduling/scripts/provider.mjs';import {digest} from '../skills/woia-scheduling/scripts/guard.mjs';
const booking={appointment_id:'a',start:'2026-10-10T10:00:00Z',end:'2026-10-10T11:00:00Z',timezone:'UTC',participant_ids:['s'],source_ref:'availability',notify_external:false};
function pair(action,payload,id='op'){const c={action,payload,operation_id:id,organization:'org',resource:'calendar',purpose:'viewing'};const x={authenticated:true,actor:'agent',organization:'org',department:'customer-service',now:100,policy_version:'p1',source_current:true,adapter_verified:true,availability:{current:true,resource:'calendar',slots:[{start:booking.start,end:booking.end}]}};x.grant={action,command_digest:digest(c),actor:'agent',organization:'org',resource:'calendar',purpose:'viewing',expires_at:200,policy_version:'p1'};return [c,x];}
const run=(s,a,p,id)=>transition(s,...pair(a,p,id));const created=()=>run(initialState(),ACTIONS[2],booking,'create').state;
test('availability and appointment reads are permitted scoped consumer subsets',()=>{for(const department of ['customer-service','sales','leasing','property-management','operations']){const [c,x]=pair(ACTIONS[0],{});x.department=department;assert.equal(transition(initialState(),c,x).result.length,1);}assert.equal(run(created(),ACTIONS[1],{appointment_id:'a'}).result.booking,'booked');});
test('create preserves distinct booking confirmation and attendance and does not notify',()=>{const a=created().appointments[0];assert.equal(a.booking,'booked');assert.equal(a.confirmation,'unknown');assert.equal(a.attendance,'unknown');assert.equal(run(initialState(),ACTIONS[2],booking).result.notification,'ROUTE_SEPARATELY_VIA_CUSTOMER_SERVICE_COMMUNICATIONS');});
test('non Customer Service cannot mutate create reschedule or cancel',()=>{for(const action of ACTIONS.slice(2,5)){const [c,x]=pair(action,{...booking,expected_version:1,reason:'change'});x.department='operations';assert.throws(()=>transition(created(),c,x),/CUSTOMER_SERVICE/);}});
test('notifications true or unspecified are rejected',()=>{for(const notify_external of [true,undefined])assert.throws(()=>run(initialState(),ACTIONS[2],{...booking,notify_external}),/NOTIFICATION/);});
test('stale availability and unavailable time fail closed',()=>{const [c,x]=pair(ACTIONS[2],booking);x.availability.current=false;assert.throws(()=>transition(initialState(),c,x),/AVAILABILITY/);assert.throws(()=>run(initialState(),ACTIONS[2],{...booking,start:'2026-10-10T12:00:00Z',end:'2026-10-10T13:00:00Z'}),/AVAILABILITY/);});
test('same slot conflict and duplicate ID never create duplicate appointment',()=>{assert.throws(()=>run(created(),ACTIONS[2],{...booking,appointment_id:'b'},'b'),/CONFLICT/);assert.throws(()=>run(created(),ACTIONS[2],booking,'new'),/DUPLICATE/);assert.equal(run(created(),ACTIONS[2],booking,'create').state.appointments.length,1);});
test('reschedule increments version and resets confirmation instead of inferring attendance',()=>{let s=created();s.appointments[0].confirmation='confirmed';const n=run(s,ACTIONS[3],{...booking,expected_version:1},'reschedule').state;assert.equal(n.appointments[0].version,2);assert.equal(n.appointments[0].confirmation,'unknown');assert.equal(n.appointments[0].attendance,'unknown');});
test('cancel changes booking only and stale command fails',()=>{const s=created();assert.throws(()=>run(s,ACTIONS[4],{appointment_id:'a',expected_version:0,reason:'human',notify_external:false}),/VERSION/);const n=run(s,ACTIONS[4],{appointment_id:'a',expected_version:1,reason:'human',notify_external:false}).state;assert.equal(n.appointments[0].booking,'cancelled');assert.equal(n.appointments[0].attendance,'unknown');});
test('reschedule never rewrites observed attendance',()=>{const s=created();s.appointments[0].attendance='attended';assert.throws(()=>run(s,ACTIONS[3],{...booking,expected_version:1}),/ATTENDANCE_IMMUTABLE/);});
test('verified status can separately observe confirmation and attendance',()=>{let s=created();for(const [kind,status] of [['confirmation','confirmed'],['attendance','attended']])s=run(s,ACTIONS[5],{appointment_id:'a',expected_version:s.appointments[0].version,kind,status,source_ref:'observed'},kind).state;assert.equal(s.appointments[0].attendance,'attended');assert.equal(s.appointments[0].booking,'booked');});
test('status cannot perform booking mutation or infer attendance without provenance',()=>{assert.throws(()=>run(created(),ACTIONS[5],{appointment_id:'a',expected_version:1,kind:'booking',status:'cancelled',source_ref:'e'}),/CUSTOMER_SERVICE/);assert.throws(()=>run(created(),ACTIONS[5],{appointment_id:'a',expected_version:1,kind:'attendance',status:'attended'}),/VERIFIED/);});
test('revoked grant and mismatched digest block the affected operation',()=>{for(const edit of [x=>x.grant.revoked=true,x=>x.grant.command_digest='bad']){const [c,x]=pair(ACTIONS[2],booking);edit(x);assert.throws(()=>transition(initialState(),c,x));}});
test('read cannot disclose another resource under scoped grant',()=>{const [c,x]=pair(ACTIONS[1],{appointment_id:'a'});c.resource='other';x.grant.resource='other';x.grant.command_digest=digest(c);assert.throws(()=>transition(created(),c,x),/NOT_FOUND/);});
